name: Jekyll site CI

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Build the site in the jekyll/builder container
       uses: actions/setup-node@v2-beta
       with:
         node-version: 12
     - name : Installling surge
       run: npm install --global surge
     - name : deploying using surge
       run: surge ./http://great-voice.surge.sh/ --token $ {{ secrets.SECOND_SECRET_CHECK }}
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
